# Generated by Django 4.1.1 on 2024-08-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=500)),
                ('Position', models.CharField(max_length=500)),
                ('Desc', models.CharField(max_length=2000)),
                ('Photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
