# Generated by Django 4.1.1 on 2024-08-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=500)),
                ('Artist', models.CharField(max_length=500)),
                ('Mediums', models.CharField(max_length=500)),
                ('Photo', models.ImageField(upload_to='')),
                ('Event', models.CharField(max_length=500)),
                ('Year', models.IntegerField()),
            ],
        ),
    ]
