# Generated by Django 5.0.4 on 2024-09-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='Photo',
            field=models.CharField(max_length=500),
        ),
    ]
